import {staticImplements} from "../utils/decorators";

export interface ViolationInterface {
    INVALID_CNPJ;
    INVALID_URL;
    FORBIDDEN_FIELD_REGISTERED;
    NO_CATEGORY_REGISTERED;
    INVALID_PASSWORD;
    INVALID_POSTAL_CODE_FORMAT;
    LENGTH_EXCEEDED;
    INVALID_EMAIL_FORMAT;
    INVALID_PHONE_FORMAT;
    INVALID_CELLPHONE_FORMAT;
    MANDATORY_FIELD;
    INVALID_FIELD;
    INVALID_CPF;
    NO_PICTURE_SELECTED;
    NO_AVATAR_SELECTED;
    NO_COMMERCIAL_DEAL_SELECTED;
}

@staticImplements<ViolationInterface>()
export class Violation {
    static NO_PICTURE_SELECTED = "NO_PICTURE_SELECTED";
    static NO_AVATAR_SELECTED = "NO_AVATAR_SELECTED";
    static INVALID_CNPJ = "INVALID_CNPJ";
    static INVALID_URL = "INVALID_URL";
    static FORBIDDEN_FIELD_REGISTERED = "FORBIDDEN_FIELD_REGISTERED";
    static NO_CATEGORY_REGISTERED = "NO_CATEGORY_REGISTERED";
    static INVALID_PASSWORD = "INVALID_PASSWORD";
    static INVALID_POSTAL_CODE_FORMAT = "INVALID_POSTAL_CODE_FORMAT";
    static LENGTH_EXCEEDED = "LENGTH_EXCEEDED";
    static INVALID_EMAIL_FORMAT = "INVALID_EMAIL_FORMAT";
    static INVALID_PHONE_FORMAT = "INVALID_PHONE_FORMAT";
    static INVALID_CELLPHONE_FORMAT = "INVALID_CELLPHONE_FORMAT";
    static MANDATORY_FIELD = "MANDATORY_FIELD";
    static INVALID_FIELD = "INVALID_FIELD";
    static INVALID_CPF = "INVALID_CPF";
    static NO_COMMERCIAL_DEAL_SELECTED = "NO_COMMERCIAL_DEAL_SELECTED";
}
